Data Preprocessing Tools

importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

KeyboardInterrupt: 

Importing dataset


In [14]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[1:9,0].values

In [15]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Taking care of missing data

In [17]:
from sklearn.impute import SimpleImputer  # Importing SimpleImputer from sklearn for handling missing values

# Creating an instance of SimpleImputer to replace missing values (np.nan) with the mean of the column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fitting the imputer on the specified columns (1 and 2) of the dataset X
imputer.fit(X[:, 1:3])

# Transforming the specified columns (1 and 2) of the dataset X using the fitted imputer
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [18]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical data

Encoding the Indepented Variable

In [19]:
from sklearn.compose import ColumnTransformer  # Importing ColumnTransformer from sklearn for applying different preprocessing steps to different columns
from sklearn.preprocessing import OneHotEncoder  # Importing OneHotEncoder from sklearn for converting categorical data to a one-hot numeric array

# Creating an instance of ColumnTransformer
# 'transformers' parameter is a list of tuples, where each tuple contains:
# - a name for the transformer ('encoder')
# - the transformer itself (OneHotEncoder())
# - the list of columns to apply the transformer to ([0])
# 'remainder' parameter specifies what to do with the remaining columns ('passthrough' means they will be left unchanged)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Applying the ColumnTransformer to the dataset X
# fit_transform() method fits the transformer to X and then transforms X
# np.array() converts the result to a NumPy array
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


encoding dependent variable

In [23]:
from sklearn.preprocessing import LabelEncoder  # Importing LabelEncoder from sklearn for converting categorical data to numeric
le= LabelEncoder()  # Creating an instance of LabelEncoder
Y =le.fit_transform(Y)  # Fitting the LabelEncoder to Y and transforming Y

In [24]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


Splitting data set into traing set and test set

In [25]:
from sklearn.model_selection import train_test_split  # Importing train_test_split from sklearn for splitting the dataset into training and test sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)  # Splitting the dataset into 80% training set and 20% test set


In [26]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [27]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [29]:
print(Y_test)

[0 1]


Feature scaling

In [32]:
from sklearn.preprocessing import StandardScaler  # Importing StandardScaler from sklearn for feature scaling

# Creating an instance of StandardScaler
sc = StandardScaler()

# Fitting the StandardScaler to the specified columns (3 and onwards) of X_train and transforming them
# fit_transform() method fits the scaler to the data and then transforms it
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:,3:]= sc.transform(X_test[:,3:])

In [31]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [33]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
